CREATE TABLE IF NOT EXISTS joueurs (
    id SERIAL PRIMARY KEY,
    pseudo VARCHAR(255) NOT NULL UNIQUE,
    argent DECIMAL(10, 2) NOT NULL DEFAULT 100.00,
    email VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255) NOT NULL,
    date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    derniere_connexion TIMESTAMP
);