spring.datasource.url=jdbc:postgresql://172.26.248.56:5432/casino_db
spring.datasource.username=tristayn
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=actuellement_en_recherche_d'une_alternance_pour_me_epanouir
jwt.expiration=86400000